name: Build RHM Sofia data

on:
  workflow_dispatch:
  schedule:
    - cron: '55 8-22/2 * * *' # At minute 55 past every 2nd hour from 8 through 22

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build-rhm-sofia

      - name: Upload rhm-sofia artifact
        uses: actions/upload-artifact@v7
        with:
          path: src/data/rhm-sofia/osm-data.json
